spring:
  application:
    name: oauth-d1
  datasource:
    url: jdbc:mysql://localhost:3306/yooeee
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
security:
  oauth2:
    resource:
      filter-order: 3
